spring:
  application:
    name: PortfolioManager
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  level:
    org.springframework.security.web.firewall: DEBUG
    org.springframework.security: DEBUG
    org.springframework.mail: DEBUG
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
portfoliomanager:
  jwt:
    secret: ${JWT_SECRET}
  language:
    defaultLanguage: en 
    availableLanguages:
      - en
      - de
  email:
    from: ${EMAIL_FROM}
    to: ${EMAIL_TO}
