spring:
  application:
    name: PortfolioManager
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio-manager
    username: portfoliomananger
    password: portfoliomanager
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  level:
    org.springframework.security.web.firewall: DEBUG
    org.springframework.security: DEBUG
    org.springframework.mail: DEBUG
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
portfoliomanager:
  jwt:
    secret: 9ZCSTjBfD5kty0YQybqa8IMwXqKnwn8wgjg8X0hxwY8=
  language:
    defaultLanguage: en 
    availableLanguages:
      - en
      - de
